# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0009_emailentry_backend'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailentry',
            name='thirdparty_reject',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
