# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-25 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0011_emailkind_fragments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailkindfragment',
            name='content',
            field=models.TextField(verbose_name='content'),
        ),
    ]
