# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-27 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0012_alter_fragment_content_verbose_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailkind',
            name='fragments',
            field=models.ManyToManyField(blank=True, related_name='kinds', to='emails.EmailKindFragment'),
        ),
    ]
