# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-01 13:46
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0013_fragments_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailentry',
            name='metadata',
            field=jsonfield.fields.JSONField(blank=True, default={}, verbose_name='Email meta fields'),
        ),
    ]
