"""
Django settings for leela project.

Generated by 'django-admin startproject' using Django 1.8.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.realpath(os.path.join(os.path.dirname(
    os.path.dirname(__file__)), '..')
)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: random key for opensource
# TODO: Change for env var in deployment 
SECRET_KEY = 'axInN&)jk=dFw^s$g(tf(wu(483nMad#/%x9)rh*f2JO$9n87vB#*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = ["127.0.0.1",
                 "localhost"]

CURRENT_HOST = 'localhost'


# Application definition
INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'djrill',
    'raven.contrib.django.raven_compat',
    'rest_framework',

    'emails',
    'emailqueue',
    'api',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)


ROOT_URLCONF = 'leela.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'admin', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'leela.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


LANGUAGES = (
    ('pt', 'Portuguese'),
    ('es', 'Spanish'),
)
DEFAULT_LANGUAGE_CODE = 'es'


MANDRILL_API_KEY = ''
DEFAULT_FROM_EMAIL = ''


# Media files. Dev values:
# Has to be overridden in production by a volume service reference and path
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/
STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'admin'),
)


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
        },
        'null': {
            'class': 'logging.NullHandler',
        },
        'sentry': {
            'level': 'WARNING',
            'class': 'raven.contrib.django.raven_compat.handlers.SentryHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
        },
        'py.warnings': {
            'handlers': ['console'],
        },
        'emails': {
            'handlers': ['sentry'],
            'level': 'WARNING',
        },
        'scheduler': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'sender': {
            'handlers': ['console'],
            'level': 'INFO'
        },
        'admin': {
            'handlers': ['sentry'],
            'level': 'WARNING',
        }
    }
}


# Queue system
RABBITMQ_HOST = 'TODO'
RABBITMQ_PORT = int('0')
RABBITMQ_USERNAME = 'guest'
RABBITMQ_PASSWORD = 'guest'
RABBITMQ_CONNECTION_ATTEMPTS = 3
RABBITMQ_EMAIL_EXCHANGE = 'root'
RABBITMQ_ENQUEUE_EMAIL_QUEUE = 'enqueue-email'
RABBITMQ_PASSIVE = True
RABBITMQ_HEARTBEAT_INTERVAL = 10


# API
REST_FRAMEWORK = {
    'PAGE_SIZE': 10
}

# Sender job
SENDER_ELLAPSED_SECONDS = 0.5

# Cleaner job
CLEANER_ELLAPSED_SECONDS = 5 * 60


# StatsD Metrics
STATSD_ENABLED = False
STATSD_HOST = 'http://example.com'
STATSD_PORT = 8125
STATSD_PREFIX = 'app.leela'
STATSD_MAXUDPSIZE = 512

METRIC = {
    'CONSUMER_RECEIVED': 'consumer.received',
    'CONSUMER_ACK': 'consumer.ack',

    'SCHEDULED_OK': 'schedule.result.ok',
    'SCHEDULED_FAIL': 'schedule.result.fail',
    'SCHEDULE_WRONG_LANG': 'schedule.wronglang',

    'CLEAN_OK': 'clean.result.ok',

    'SEND_OK': 'send.result.ok',
    'SEND_FAIL': 'send.result.fail',
    'SEND_IS_SPAM': 'send.spam',
    'SEND_ATTACHS': 'send.attachs',
}

# HTML minification
MINIFY_HTML = True
